### ISSUE TITLE
Couldn't find env file

### ISSUE THREAD

**Issue by Kolhax** [jaypyles/Scraperr#29]
F:\Scraperr-master>make up
docker compose -f docker-compose.yml --env-file .env up -d --force-recreate
Couldn't find env file: F:\Scraperr-master\.env
make: *** [Makefile:40: up] Error 15

F:\Scraperr-master>

**Comment by jaypyles** [comment]
If you look at the command the Makefile is running, it is clearly stating that it is looking for an `env` file named `.env`. So either change your compose file and your name of your `env` file or change the command the Makefile is running.
