### ISSUE TITLE
Scraping via Site Mapping

### ISSUE THREAD

**Issue by jaypyles** [jaypyles/Scraperr#33]
As a user, I would like to be able to create a series of steps to take to collect data on a website. 

Ex: Click the next button on every page to go to the next page.

**Comment by thenightbeliever** [comment]
I was wondering if it’s possible to apply this, especially on a page with pagination?

**Comment by jaypyles** [comment]
> I was wondering if it’s possible to apply this, especially on a page with pagination?

Just merged this change in now. Try it out
