### ISSUE TITLE
It seems the clean_xpath() function didn't clean the xpath

### ISSUE THREAD

**Issue by hunterMG** [jaypyles/Scraperr#42]
**Describe the bug**
Xpath can't get the information I want to extract from the webpage.
**To Reproduce**
URL:   https://news.yiche.com/xinchexiaoxi/
xpath:   `//h3[@class="title"]/text()`

**Screenshots**
![Snipaste_2024-11-11_17-02-09](https://github.com/user-attachments/assets/87c0186f-412a-48bd-8f9a-e5fb88870e36)

![Snipaste_2024-11-11_16-54-11](https://github.com/user-attachments/assets/0808c2e1-bf21-45da-a1ff-f05ee6fac8cb)

**Comment by hunterMG** [comment]
Thanks. My bad, but maybe it should be put in the doc/README.

**Comment by jaypyles** [comment]
Noted.
