### ISSUE TITLE
Issues with scrapy.py file with [ Scrap jobs ]  + My solution.

### ISSUE THREAD

**Issue by n0c3Nz** [jaypyles/Scraperr#50]
Hey howdy, I have detected that there is a bug in the `scrapy.py` file that causes failure in every single scrap job we do, I am running docker from an **Ubuntu 5.15.0-126-generic**, the data is not well collected when serving the information and I have fixed it by replacing this line:

```py
text = "\t".join(str(t) for t in e.itertext())
```
with this:

```py
if isinstance(e, etree._Element):
        text = "\t".join(str(t) for t in e.itertext())
    else:
        text = str(e)
```

So I have had no more problems and it scrapes to the end haha, hope I helped, best regards and thank you for your work.

**Comment by jaypyles** [comment]
Submit a PR and I'll merge it in
